# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  github-cli: circleci/github-cli@2.5.0
  rust: circleci/rust@1.7.0

executors:
  unknown_linux:
    docker:
      - image: cimg/rust:1.73.0
  mseries_mac:
    macos:
      xcode: "16.4.0"
    resource_class: m1.medium

commands:
  build-and-test-unix-like:
    steps:
      - run:
          name: Build
          command: cargo build
      - run:
          # TODO: make this run a useful thing
          name: test build
          command: bash test/test.sh
      - run:
          name: move build to useful place
          command: |
            mkdir tmp/
            mv target/debug/net-task tmp/
      # TODO: we want to bootstrap this way, or not??

  release-build:
    steps:
      - run:
          name: build release package
          command: tmp/net-task -t ./net-task-ci.yml run ci:create-arch-tagged-release
      - run:
          name: temp move binary over
          command: mv tmp/net-task target/net-task/net-task-tmp

jobs:
  build_macos:
    executor: mseries_mac
    steps:
      - rust/install
      - checkout
      - build-and-test-unix-like
      - release-build

  build:
    executor: unknown_linux

    steps:
      - checkout
      - build-and-test-unix-like
      - release-build
      - persist_to_workspace:
          root: target/
          paths:
            - net-task/

  release:
    docker:
      - image: cimg/rust:1.73.0
    steps:
      - github-cli/install
      # checkout to get the net-task files.
      # ... could also use a URL, I guess....
      - checkout
      - attach_workspace:
          at: built-binaries
      - run:
          name: github authorize
          command: built-binaries/net-task/net-task-tmp -t ./net-task-ci.yml run ci:gh:auth
      - run:
          name: upload binaries to release (optional)
          command: built-binaries/net-task/net-task-tmp -t ./net-task-ci.yml run ci:gh:upload-binary



# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  feature-branch-test:
    jobs:
      - build
      - build_macos
      - release:
          requires:
            - build
          context:
            - github
